# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Merge me!
        uses: ridedott/merge-me-action@v1.2.62
        with:
          # A GitHub token.
          GITHUB_TOKEN: 8de32fbb30ade7e9b9718cd17c2d7912f111d8bb
          # The GitHub login for which automatic merges are enabled.
          GITHUB_LOGIN: avpeace
          # Represents available types of methods to use when merging a pull request. One of: MERGE, STASH or REBASE
          MERGE_METHOD: # optional, default is SQUASH
